name: CI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download exe, Scan, and Extract Stats
        id: vt_scan
        env:
          VT_API_KEY: ${{ secrets.VT_API_KEY }}
        run: |
          echo "Downloading kwype.exe..."
          curl -L -o kwype.exe "https://github.com/Saikyo0/Kwype-App/releases/latest/download/kwype.exe"
          
          echo "Getting VT Upload URL..."
          UPLOAD_URL=$(curl --silent --request GET \
            --url https://www.virustotal.com/api/v3/files/upload_url \
            --header 'accept: application/json' \
            --header "x-apikey: $VT_API_KEY" | jq -r '.data')
          
          echo "Uploading file to VirusTotal..."
          ANALYSIS_JSON=$(curl --silent --request POST \
            --url "$UPLOAD_URL" \
            --header 'accept: application/json' \
            --header "x-apikey: $VT_API_KEY" \
            --form file=@kwype.exe)
          
          ANALYSIS_ID=$(echo $ANALYSIS_JSON | jq -r '.data.id')
          echo "Analysis ID: $ANALYSIS_ID"
          
          STATUS="queued"
          echo "Waiting for scan to complete..."
          
          while [[ "$STATUS" != "completed" ]]; do
            sleep 15
            REPORT_JSON=$(curl --silent --request GET \
              --url "https://www.virustotal.com/api/v3/analyses/$ANALYSIS_ID" \
              --header 'accept: application/json' \
              --header "x-apikey: $VT_API_KEY")
            
            STATUS=$(echo $REPORT_JSON | jq -r '.data.attributes.status')
            echo "Current Status: $STATUS"
          done
          
          echo "Scan Finished. Extracting Data..."
          
          MALICIOUS=$(echo $REPORT_JSON | jq -r '.data.attributes.stats.malicious')
          SUSPICIOUS=$(echo $REPORT_JSON | jq -r '.data.attributes.stats.suspicious')
          UNDETECTED=$(echo $REPORT_JSON | jq -r '.data.attributes.stats.undetected')
          HASH=$(echo $REPORT_JSON | jq -r '.meta.file_info.sha256')

          echo "malicious=$MALICIOUS" >> $GITHUB_OUTPUT
          echo "suspicious=$SUSPICIOUS" >> $GITHUB_OUTPUT
          echo "undetected=$UNDETECTED" >> $GITHUB_OUTPUT
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Format Badges
        id: badges
        run: |
        
          BADGE_MAL="![Malicious](https://img.shields.io/badge/Malicious-${{ steps.vt_scan.outputs.malicious }}-red?style=for-the-badge)"
          BADGE_SUS="![Suspicious](https://img.shields.io/badge/Suspicious-${{ steps.vt_scan.outputs.suspicious }}-yellow?style=for-the-badge)"
          BADGE_CLN="![Clean](https://img.shields.io/badge/Clean-${{ steps.vt_scan.outputs.undetected }}-green?style=for-the-badge)"
          LINK="[VirusTotal Report](https://www.virustotal.com/gui/file/${{ steps.vt_scan.outputs.hash }})"
          
          ALL_BADGES="$BADGE_CLN $BADGE_MAL $BADGE_SUS <br> $LINK"
          
          echo "badge_string=$ALL_BADGES" >> $GITHUB_OUTPUT

      - name: Update Repo README
        uses: theboi/github-update-readme@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        with:
        
          header: "Kwype <br> <img width='128' height='128' alt='Kwype Logo' src='https://github.com/user-attachments/assets/8ecc8e51-82e1-407c-bf52-b7354933e870' /> <br><br>"
          subhead: "${{ steps.badges.outputs.badge_string }} <br><br>KwYPE explores what happens when mobile-style gesture typing is brought to physical keyboards. <br><br>The main incentive for this project is **accessibility**! <br><br>Swipe gestures reduce repetitive key presses, making typing more comfortable for users with arthritis, RSI, or limited dexterity."
          footer: "**Hosted on: [kwype.app](https://kwype.netlify.app)!**"
          ref: "main"
          
          
