name: CI

# Controls when the workflow will run
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Download zip, Scan, and Return Results
        id: vt_scan
        env:
          VT_API_KEY: ${{ secrets.VT_API_KEY }}
          
        run: |
          echo "Downloading Kwype.zip..."
          curl -L -o Kwype.zip "https://github.com/Saikyo0/Kwype-App/releases/latest/download/Kwype.zip"
        
          echo "Getting VT Upload URL..."
          UPLOAD_URL=$(curl --silent --request GET \
            --url https://www.virustotal.com/api/v3/files/upload_url \
            --header 'accept: application/json' \
            --header "x-apikey: $VT_API_KEY" | jq -r '.data' )
        
          echo "Uploading file to VirusTotal..."
          ANALYSIS_JSON=$(curl --silent --request POST \
            --url "$UPLOAD_URL" \
            --header 'accept: application/json' \
            --header "x-apikey: $VT_API_KEY" \
            --form file=@Kwype.zip )
          ANALYSIS_ID=$(echo $ANALYSIS_JSON | jq -r '.data.id')
          echo "File uploaded. Analysis ID: $ANALYSIS_ID"
          
          STATUS="queued"
          echo "Waiting for scan to complete..."
          while [[ "$STATUS" != "completed" ]]; do
            sleep 15
            REPORT_JSON=$(curl --silent --request GET \
              --url "https://www.virustotal.com/api/v3/analyses/$ANALYSIS_ID" \
              --header 'accept: application/json' \
              --header "x-apikey: $VT_API_KEY" )
            STATUS=$(echo $REPORT_JSON | jq -r '.data.attributes.status')
            echo "Current Status: $STATUS"
          done

          MALICIOUS_COUNT=$(echo $REPORT_JSON | jq -r '.data.attributes.stats.malicious')
          GUI_LINK=$(echo $REPORT_JSON | jq -r '.data.links.self')
          echo "Scan Finished."
          echo "Malicious Detections: $MALICIOUS_COUNT"
          echo "Report Link: $GUI_LINK"
          echo "vt_url=$GUI_LINK" >> $GITHUB_OUTPUT

      - name: Print Success Tag
        if: success()
        run: |
          echo "Report: ${{ steps.vt_scan.outputs.vt_url }}"
